### ISSUE TITLE
IndexOutOfBounds exception while indexing

### ISSUE THREAD

**Issue by bgamari** [carymrobbins/intellij-haskforce#164]
This [log](https://gist.github.com/bgamari/bec0b24087b935b7ab46) shows an `IndexOutOfBounds` exception thrown by Idea apparently while HaskForce was indexing.

I'm afraid I'm relying on old notes from a friend for the details of the issue. I can ask for more detail if necessary.

**Comment by carymrobbins** [comment]
@bgamari - Would you be able to provide a gist of the `Setup.hs` file referenced in that thread dump?  Also, does this seem to impact usability of the IDE?

**Technical Note**

This _might_ be related to #76.

Note that the only frames that reference `com.haskforce` are -

```
 	at com.haskforce.highlighting.annotation.external.TypeInfoUtil.getTypeInfo(TypeInfoUtil.java:36)
	at com.haskforce.highlighting.annotation.HaskellDocumentationProvider.generateDoc(HaskellDocumentationProvider.java:21)
```

Although, this looks like it is probably from a separate thread and not related to indexing.

**Comment by bgamari** [comment]
If I'm not mistaken there was nothing special about the `Setup.hs` file but let me get back to you on that

If I recall correctly we noticed this error as the "Quick Documentation" feature did nothing when invoked. I'll try to reproduce again.

**Comment by carymrobbins** [comment]
Interesting, particularly since I noticed the Type Info / Documentation Provider frames in the thread dump.

**Comment by PetrGlad** [comment]
I am not sure if this a separate issue but I see many of these exceptions (Intellij Ultimate 14.1.4):
```
Index: 0
java.lang.IndexOutOfBoundsException: Index: 0
	at com.intellij.util.containers.ContainerUtilRt$EmptyList.get(ContainerUtilRt.java:314)
	at com.haskforce.psi.references.HaskellReference.multiResolve(HaskellReference.java:98)
	at com.haskforce.psi.references.HaskellReference.resolve(HaskellReference.java:236)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:330)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:95)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:201)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:60)
	at cursive.findUsages.highlight.ClojureHighlightUsagesHandlerFactory.createHighlightUsagesHandler(ClojureHighlightUsagesHandlerFactory.java:45)
	at com.intellij.codeInsight.highlighting.HighlightUsagesHandlerFactoryBase.createHighlightUsagesHandler(HighlightUsagesHandlerFactoryBase.java:35)
	at com.intellij.codeInsight.highlighting.HighlightUsagesHandler.createCustomHandler(HighlightUsagesHandler.java:163)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:71)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:189)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by carymrobbins** [comment]
@PetrGlad - Hmm, it's strange, because it seems that `cursive` is in the stack trace.  It's as though Cursive is trying to highlight usages in a Haskell file.  This seems like a separate issue, but I'll have to dig in more to confirm.

**Comment by PetrGlad** [comment]
I did not notice this. I'll ping Cursive's author also.

**Comment by carymrobbins** [comment]
I actually spoke with him already.  Either way, HaskForce should probably handle this better.

**Comment by carymrobbins** [comment]
This should be resolved as of **0.3-beta.27**.

**Comment by LeanderK** [comment]
it is not resolved. I am currently debugging with the changes active and still get the IndexOutOfBounds. 

```java
[ 135467]  ERROR - napi.project.CacheUpdateRunner - Error while indexing /Users/LeanderK/IdeaProjects/iris/src/Iris/Camera/PanZoom.hs
To reindex this file IDEA has to be restarted 
java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.CharBuffer.charAt(CharBuffer.java:1278)
	at com.intellij.lang.cacheBuilder.DefaultWordsScanner.stripWords(DefaultWordsScanner.java:107)
	at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:78)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:119)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:106)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:85)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:79)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:457)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1633)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1559)
	at com.intellij.util.indexing.FileBasedIndexImpl$$Lambda$553/1614750722.run(Unknown Source)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:505)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1516)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1501)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:107)
	at com.intellij.util.indexing.UnindexedFilesUpdater$$Lambda$543/735105035.consume(Unknown Source)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:219)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$$Lambda$548/1994059979.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1034)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:236)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$$Lambda$552/2015170656.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
[This](https://github.com/jdreaver/iris) is the project i am testing it with.
Is this an intellij bug? there is no haskforce in the stack trace.
