### ISSUE TITLE
haskforce plugin breaks importing other project types

### ISSUE THREAD

**Issue by joprice** [carymrobbins/intellij-haskforce#227]
When importing an sbt project with haskforce plugin installed, the haskforce project throws an exception and intellij silently ignores my import request. 

It looks like another `!fileOrDirectory.isDirectory` is required on when filtering children.

https://github.com/carymrobbins/intellij-haskforce/blob/v0.3-beta.25/src/com/haskforce/importWizard/stack/StackProjectImportProvider.scala#L27

```
Caused by: java.io.IOException: Cannot get content of directory
at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.contentsToByteArray(VirtualDirectoryImpl.java:421)
	at com.haskforce.importWizard.stack.StackProjectImportProvider.canImportFromFile(StackProjectImportProvider.scala:36)
	at com.haskforce.importWizard.stack.StackProjectImportProvider$$anonfun$canImport$2.apply(StackProjectImportProvider.scala:28)
	at com.haskforce.importWizard.stack.StackProjectImportProvider$$anonfun$canImport$2.apply(StackProjectImportProvider.scala:28)
	at scala.collection.IndexedSeqOptimized$class.prefixLengthImpl(IndexedSeqOptimized.scala:38)
```

**Comment by carymrobbins** [comment]
I plan on making a release later tonight, so I'll include the fix for this.  Thanks for the report!

**Comment by carymrobbins** [comment]
@joprice - This should be resolved in the latest release, **0.3-beta.26**.  Please reopen if you encounter any issues.

**Comment by joprice** [comment]
No problem. When should I expect to see it in the plugin search? I still see 25.

**Comment by carymrobbins** [comment]
@joprice - Maybe it would help if I'd actually upload the release to Jetbrains' repo.

It should be available now, sorry about that!

**Comment by joprice** [comment]
Thanks! I was just able to install it and import both a haskell and sbt based project.

**Comment by carymrobbins** [comment]
Sounds good, thanks again for the report @joprice!
